modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/cech12/CeramicShears/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="ceramicshears"
    version="${file.jarVersion}"
    displayName="Ceramic Shears"
    displayURL="https://github.com/cech12/CeramicShears"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds Ceramic Shears.
    '''
[[dependencies.ceramicshears]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.23,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ceramicshears]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"